# ==========================
# SonarCloud Configuration
# ==========================

# SonarCloud URL
sonar.host.url=https://sonarcloud.io

# Organization Key
sonar.organization=anshika7820

# Project Key
sonar.projectKey=Anshika7820_starbucks

# Project Name
sonar.projectName=starbucks

# Project Version
sonar.projectVersion=1.0

# Source Folder
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude folders
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js,**/*.spec.js

# JavaScript / React
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Optional (ignore generated files)
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**,**/build/**

# Optional (ignore images/fonts)
sonar.cpd.exclusions=**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.webp,**/*.woff,**/*.woff2,**/*.ttf
